import React, { useCallback } from "react";
import { useForm } from "react-hook-form";
import { Button, Input, RTE, Select } from "..";             // byDefault it is from : index.js 
import appwriteService from "../../appwrite/config";
import { useNavigate } from "react-router-dom";
import { useSelector } from "react-redux";

export default function PostForm({ post }) {
    const { register, handleSubmit, watch, setValue, control, getValues } = useForm({
        defaultValues: {
            title: post?.title || "",
            slug: post?.$id || "",
            content: post?.content || "",
            status: post?.status || "active",
        },
    });

    const navigate = useNavigate();
    const userData = useSelector((state) => state.auth.userData);  // jo hmari authSlice hai uska name : "auth" hai therefore : state.auth.userData 

    const submit = async (data) => {

        if (post) { // if post already exists => update the post : 
            const file = data.image[0] ? await appwriteService.uploadFile(data.image[0]) : null;
// data.image is a array of images because multiple images are also supported in appwrite but data.image[0] = first image of that array. 
// uploadFile function uploaded the file and returned the fileId generated by appwrite which we can store in our posts table. ; this fileId corresponds to actual image.

            if (file) { // if we got a new file then we delete the old file.
                appwriteService.deleteFile(post.featuredImage);
            } 
            // what is post.featuredImage : in our appwrite database(BlogData) we have article table in which there is a featuredImage field storing fileId of image.

            const dbPost = await appwriteService.updatePost(post.$id, {
                ...data,
                featuredImage: file ? file.$id : undefined,
            });

            if (dbPost) {
                navigate(`/post/${dbPost.$id}`);
            }
        } else { // create newn post.
            // if image is given upload it.
            const file = data.image[0] ? await appwriteService.uploadFile(data.image[0]) : null;

            if (file) {
                const fileId = file.$id;
                data.featuredImage = fileId;
                const dbPost = await appwriteService.createPost({
                     ...data,                  // ye jo data user ne dia h usme kabhib bhi userid field nahi ho sakta as user dont know their id .. so userid Slice se utha lia
                      userId: userData.$id     // user data hamne auth ki state se uthaya tha.
                    });
                    // createpost return post data after post creation.
                if (dbPost) {
                    navigate(`/post/${dbPost.$id}`);
                }
            }
        }
    };

    // Imp react concept : transform ' ' => '-' on realtime in input containers.
    const slugTransform = useCallback((value) => {  // take some string value in input and return transformed string.
        if (value && typeof value === "string")
            return value
                .trim()
                .toLowerCase()
                .replace(/[^a-zA-Z\d\s]+/g, "-")  // ^ means negation ; \d = digits ; \s = spaces ; replace all specail chars by "-"
                .replace(/\s/g, "-");             // replace all spaces by "-" ; this is regex.

        return "";
    }, []);

    // properly explained this useEffect and useCallback part in notes. (IMP concept)
    React.useEffect(() => {
        const subscription = watch((value, { name }) => {
            if (name === "title") {
                setValue("slug", slugTransform(value.title), { shouldValidate: true });
            }
        });

        return () => subscription.unsubscribe();
    }, [watch, slugTransform, setValue]);

    return (
        <form onSubmit={handleSubmit(submit)} className="flex flex-wrap">
            {/* first part is left part of form - taking 2/3rd width. */}
            <div className="w-2/3 px-2">
                
                <Input
                    label="Title :"
                    placeholder="Title"
                    className="mb-4"
                    {...register("title", { required: true })}
                />

                {/* register connect input fields to react-hook-from. ;
                 register is a method of react-hook-form;
                 compulsory hai har Field ko react-hook-from se to connect krna hi hoga. */}
                
                <Input
                    label="Slug :"
                    placeholder="Slug"
                    className="mb-4"
                    {...register("slug", { required: true })}
                    onInput={(e) => {
                        setValue("slug", slugTransform(e.currentTarget.value), { shouldValidate: true });
                    }}
                />
                {/* IMP question : why onInput is applied even if useEffect is there . */}

                {/* RTE : real time editor */}
                <RTE label="Content :" name="content" control={control} defaultValue={getValues("content")} />
            </div>

            {/* The right part : 1/3rd width.  */}
            <div className="w-1/3 px-2">
                <Input
                    label="Featured Image :"
                    type="file"
                    className="mb-4"
                    accept="image/png, image/jpg, image/jpeg, image/gif"
                    {...register("image", { required: !post })}
                />
                {post && (
                    <div className="w-full mb-4">
                        <img
                            src={appwriteService.getFilePreview(post.featuredImage)}
                            alt={post.title}
                            className="rounded-lg"
                        />
                    </div>
                )}
                <Select
                    options={["active", "inactive"]}
                    label="Status"
                    className="mb-4"
                    {...register("status", { required: true })}
                />
                <Button type="submit" bgColor={post ? "bg-green-500" : undefined} className="w-full">
                    {post ? "Update" : "Submit"}
                </Button>
            </div>
        </form>
    );
}